spring.application.name=chat-service
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=openai/gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.4
